version: 2.1


jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    
    
    working_directory: ~/repo
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
          name: install dependencies
          
      - save_cache:
          paths:
            - ./venv
          key:  v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          command: |
            . venv/bin/activate
            make lint
          name: run lint

workflows:
  main:
    jobs:
      - build-and-test
